name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Show OS Information
        run: uname -a

      - name: Print Message
        run: echo "Hello from GitHub Actions"